use_frameworks!

platform :ios, '9.0'

target 'myComponentKit_Example' do
  pod 'myComponentKit', :path => '../'

  target 'myComponentKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
